### ISSUE TITLE
overwriting of symlinks to files outside the grunt directory fails 

### ISSUE THREAD

**Issue by iislucas** [gruntjs/grunt-contrib-symlink#12]
With `overwrite: true` set, if a symlink resolves to a file outside of the gruntfile's directory, then when it attempts to overwrite an old symlink it fails with:  `Warning: Cannot delete files outside the current working directory. Use --force to continue.`

I think it should just unlink/change the old symlink.

**Comment by mseankelly** [comment]
I'm on a Windows machine, and the following does not work:

    options: {
        overwrite: false,
        force: true
    }

I still get the following warning: `Cannot delete files outside the current working directory. Use --force
to continue.`

**Comment by rfludwick** [comment]
This is also causing a problem for me.

**Comment by liverbool** [comment]
me too.

**Comment by woutrbe** [comment]
Same issue here, running the command with --force appears to work.

**Comment by woutrbe** [comment]
Looks like a fix was actually merged: https://github.com/gruntjs/grunt-contrib-symlink/commit/21c520c9abd8dca4e5e56a9b3dab1d91bce3d614

**Comment by afewyards** [comment]
You might want to publish a release after that patch... as npm is not picking it up

**Comment by pleszczynski** [comment]
Is this going to be published on npm? Last published version is from 2014, and this is rather big fix.

**Comment by stvkas** [comment]
@pleszczynski I just downloaded version 0.3.0 from npm and it's working for me.

**Comment by brianhelba** [comment]
To be clear, this bug has always been present when using NodeJS 5.x, and it is *not* fixed in the 0.3.0 release of ``grunt-contrib-symlink``. @stvkas , I assume you were using NodeJS 4.x or earlier.

This was fixed in master over 16 months ago, from https://github.com/gruntjs/grunt-contrib-symlink/pull/13 , but we desperately need a new release to close this issue and https://github.com/gruntjs/grunt-contrib-symlink/issues/21 .

@shama This is a very useful tool, but if it's not kept updated, the user base may fork and fragment. You appear to be a maintainer [on npmjs.com](https://www.npmjs.com/package/grunt-contrib-symlink), are you able to push a new release? Please let me know if you require any assistance.

**Comment by shama** [comment]
Published as `1.0.0`.
